export const countryOptions: { value: string; label: string }[] = [
	{ value: 'andorra', label: 'Andorra' },
	{ value: 'united arab emirates', label: 'United Arab Emirates' },
	{ value: 'afghanistan', label: 'Afghanistan' },
	{ value: 'antigua and barbuda', label: 'Antigua and Barbuda' },
	{ value: 'anguilla', label: 'Anguilla' },
	{ value: 'albania', label: 'Albania' },
	{ value: 'armenia', label: 'Armenia' },
	{ value: 'angola', label: 'Angola' },
	{ value: 'antarctica', label: 'Antarctica' },
	{ value: 'argentina', label: 'Argentina' },
	{ value: 'american samoa', label: 'American Samoa' },
	{ value: 'austria', label: 'Austria' },
	{ value: 'australia', label: 'Australia' },
	{ value: 'aruba', label: 'Aruba' },
	{ value: 'åland islands', label: 'Åland Islands' },
	{ value: 'azerbaijan', label: 'Azerbaijan' },
	{ value: 'bosnia and herzegovina', label: 'Bosnia and Herzegovina' },
	{ value: 'barbados', label: 'Barbados' },
	{ value: 'bangladesh', label: 'Bangladesh' },
	{ value: 'belgium', label: 'Belgium' },
	{ value: 'burkina faso', label: 'Burkina Faso' },
	{ value: 'bulgaria', label: 'Bulgaria' },
	{ value: 'bahrain', label: 'Bahrain' },
	{ value: 'burundi', label: 'Burundi' },
	{ value: 'benin', label: 'Benin' },
	{ value: 'saint barthélemy', label: 'Saint Barthélemy' },
	{ value: 'bermuda', label: 'Bermuda' },
	{ value: 'brunei', label: 'Brunei' },
	{ value: 'bolivia', label: 'Bolivia' },
	{ value: 'caribbean netherlands', label: 'Caribbean Netherlands' },
	{ value: 'brazil', label: 'Brazil' },
	{ value: 'bahamas', label: 'Bahamas' },
	{ value: 'bhutan', label: 'Bhutan' },
	{ value: 'bouvet island', label: 'Bouvet Island' },
	{ value: 'botswana', label: 'Botswana' },
	{ value: 'belarus', label: 'Belarus' },
	{ value: 'belize', label: 'Belize' },
	{ value: 'canada', label: 'Canada' },
	{ value: 'cocos (keeling) islands', label: 'Cocos (Keeling) Islands' },
	{ value: 'democratic republic of the congo', label: 'Democratic Republic of the Congo' },
	{ value: 'central african republic', label: 'Central African Republic' },
	{ value: 'republic of the congo', label: 'Republic of the Congo' },
	{ value: 'switzerland', label: 'Switzerland' },
	{ value: 'côte d`ivoire', label: 'Côte d`Ivoire' },
	{ value: 'cook islands', label: 'Cook Islands' },
	{ value: 'chile', label: 'Chile' },
	{ value: 'cameroon', label: 'Cameroon' },
	{ value: 'china', label: 'China' },
	{ value: 'colombia', label: 'Colombia' },
	{ value: 'costa rica', label: 'Costa Rica' },
	{ value: 'cuba', label: 'Cuba' },
	{ value: 'cape verde', label: 'Cape Verde' },
	{ value: 'curaçao', label: 'Curaçao' },
	{ value: 'christmas island', label: 'Christmas Island' },
	{ value: 'cyprus', label: 'Cyprus' },
	{ value: 'czech republic', label: 'Czech Republic' },
	{ value: 'germany', label: 'Germany' },
	{ value: 'djibouti', label: 'Djibouti' },
	{ value: 'denmark', label: 'Denmark' },
	{ value: 'dominica', label: 'Dominica' },
	{ value: 'dominican republic', label: 'Dominican Republic' },
	{ value: 'algeria', label: 'Algeria' },
	{ value: 'ecuador', label: 'Ecuador' },
	{ value: 'estonia', label: 'Estonia' },
	{ value: 'egypt', label: 'Egypt' },
	{ value: 'western sahara', label: 'Western Sahara' },
	{ value: 'eritrea', label: 'Eritrea' },
	{ value: 'spain', label: 'Spain' },
	{ value: 'ethiopia', label: 'Ethiopia' },
	{ value: 'finland', label: 'Finland' },
	{ value: 'fiji', label: 'Fiji' },
	{ value: 'falkland islands', label: 'Falkland Islands' },
	{ value: 'micronesia', label: 'Micronesia' },
	{ value: 'faroe islands', label: 'Faroe Islands' },
	{ value: 'france', label: 'France' },
	{ value: 'gabon', label: 'Gabon' },
	{ value: 'united kingdom', label: 'United Kingdom' },
	{ value: 'grenada', label: 'Grenada' },
	{ value: 'georgia', label: 'Georgia' },
	{ value: 'french guiana', label: 'French Guiana' },
	{ value: 'guernsey', label: 'Guernsey' },
	{ value: 'ghana', label: 'Ghana' },
	{ value: 'gibraltar', label: 'Gibraltar' },
	{ value: 'greenland', label: 'Greenland' },
	{ value: 'gambia', label: 'Gambia' },
	{ value: 'guinea', label: 'Guinea' },
	{ value: 'guadeloupe', label: 'Guadeloupe' },
	{ value: 'equatorial guinea', label: 'Equatorial Guinea' },
	{ value: 'greece', label: 'Greece' },
	{ value: 'south georgia and the south sandwich islands', label: 'South Georgia and the South Sandwich Islands' },
	{ value: 'guatemala', label: 'Guatemala' },
	{ value: 'guam', label: 'Guam' },
	{ value: 'guinea-bissau', label: 'Guinea-Bissau' },
	{ value: 'guyana', label: 'Guyana' },
	{ value: 'hong kong', label: 'Hong Kong' },
	{ value: 'heard island and mcdonald islands', label: 'Heard Island and McDonald Islands' },
	{ value: 'honduras', label: 'Honduras' },
	{ value: 'croatia', label: 'Croatia' },
	{ value: 'haiti', label: 'Haiti' },
	{ value: 'hungary', label: 'Hungary' },
	{ value: 'indonesia', label: 'Indonesia' },
	{ value: 'ireland', label: 'Ireland' },
	{ value: 'israel', label: 'Israel' },
	{ value: 'isle of man', label: 'Isle of Man' },
	{ value: 'india', label: 'India' },
	{ value: 'british indian ocean territory', label: 'British Indian Ocean Territory' },
	{ value: 'iraq', label: 'Iraq' },
	{ value: 'iran', label: 'Iran' },
	{ value: 'iceland', label: 'Iceland' },
	{ value: 'italy', label: 'Italy' },
	{ value: 'jersey', label: 'Jersey' },
	{ value: 'jamaica', label: 'Jamaica' },
	{ value: 'jordan', label: 'Jordan' },
	{ value: 'japan', label: 'Japan' },
	{ value: 'kenya', label: 'Kenya' },
	{ value: 'kyrgyzstan', label: 'Kyrgyzstan' },
	{ value: 'cambodia', label: 'Cambodia' },
	{ value: 'kiribati', label: 'Kiribati' },
	{ value: 'comoros', label: 'Comoros' },
	{ value: 'saint kitts and nevis', label: 'Saint Kitts and Nevis' },
	{ value: 'north korea', label: 'North Korea' },
	{ value: 'south korea', label: 'South Korea' },
	{ value: 'kuwait', label: 'Kuwait' },
	{ value: 'cayman islands', label: 'Cayman Islands' },
	{ value: 'kazakhstan', label: 'Kazakhstan' },
	{ value: 'laos', label: 'Laos' },
	{ value: 'lebanon', label: 'Lebanon' },
	{ value: 'saint lucia', label: 'Saint Lucia' },
	{ value: 'liechtenstein', label: 'Liechtenstein' },
	{ value: 'sri lanka', label: 'Sri Lanka' },
	{ value: 'liberia', label: 'Liberia' },
	{ value: 'lesotho', label: 'Lesotho' },
	{ value: 'lithuania', label: 'Lithuania' },
	{ value: 'luxembourg', label: 'Luxembourg' },
	{ value: 'latvia', label: 'Latvia' },
	{ value: 'libya', label: 'Libya' },
	{ value: 'morocco', label: 'Morocco' },
	{ value: 'monaco', label: 'Monaco' },
	{ value: 'moldova', label: 'Moldova' },
	{ value: 'montenegro', label: 'Montenegro' },
	{ value: 'saint martin', label: 'Saint Martin' },
	{ value: 'madagascar', label: 'Madagascar' },
	{ value: 'marshall islands', label: 'Marshall Islands' },
	{ value: 'north macedonia', label: 'North Macedonia' },
	{ value: 'mali', label: 'Mali' },
	{ value: 'myanmar', label: 'Myanmar' },
	{ value: 'mongolia', label: 'Mongolia' },
	{ value: 'macao', label: 'Macao' },
	{ value: 'northern mariana islands', label: 'Northern Mariana Islands' },
	{ value: 'martinique', label: 'Martinique' },
	{ value: 'mauritania', label: 'Mauritania' },
	{ value: 'montserrat', label: 'Montserrat' },
	{ value: 'malta', label: 'Malta' },
	{ value: 'mauritius', label: 'Mauritius' },
	{ value: 'maldives', label: 'Maldives' },
	{ value: 'malawi', label: 'Malawi' },
	{ value: 'mexico', label: 'Mexico' },
	{ value: 'malaysia', label: 'Malaysia' },
	{ value: 'mozambique', label: 'Mozambique' },
	{ value: 'namibia', label: 'Namibia' },
	{ value: 'new caledonia', label: 'New Caledonia' },
	{ value: 'niger', label: 'Niger' },
	{ value: 'norfolk island', label: 'Norfolk Island' },
	{ value: 'nigeria', label: 'Nigeria' },
	{ value: 'nicaragua', label: 'Nicaragua' },
	{ value: 'netherlands', label: 'Netherlands' },
	{ value: 'norway', label: 'Norway' },
	{ value: 'nepal', label: 'Nepal' },
	{ value: 'nauru', label: 'Nauru' },
	{ value: 'niue', label: 'Niue' },
	{ value: 'new zealand', label: 'New Zealand' },
	{ value: 'oman', label: 'Oman' },
	{ value: 'panama', label: 'Panama' },
	{ value: 'peru', label: 'Peru' },
	{ value: 'french polynesia', label: 'French Polynesia' },
	{ value: 'papua new guinea', label: 'Papua New Guinea' },
	{ value: 'philippines', label: 'Philippines' },
	{ value: 'pakistan', label: 'Pakistan' },
	{ value: 'poland', label: 'Poland' },
	{ value: 'saint pierre and miquelon', label: 'Saint Pierre and Miquelon' },
	{ value: 'pitcairn', label: 'Pitcairn' },
	{ value: 'puerto rico', label: 'Puerto Rico' },
	{ value: 'palestine', label: 'Palestine' },
	{ value: 'portugal', label: 'Portugal' },
	{ value: 'palau', label: 'Palau' },
	{ value: 'paraguay', label: 'Paraguay' },
	{ value: 'qatar', label: 'Qatar' },
	{ value: 'réunion', label: 'Réunion' },
	{ value: 'romania', label: 'Romania' },
	{ value: 'serbia', label: 'Serbia' },
	{ value: 'russia', label: 'Russia' },
	{ value: 'rwanda', label: 'Rwanda' },
	{ value: 'saudi arabia', label: 'Saudi Arabia' },
	{ value: 'solomon islands', label: 'Solomon Islands' },
	{ value: 'seychelles', label: 'Seychelles' },
	{ value: 'sudan', label: 'Sudan' },
	{ value: 'sweden', label: 'Sweden' },
	{ value: 'singapore', label: 'Singapore' },
	{ value: 'saint helena', label: 'Saint Helena' },
	{ value: 'slovenia', label: 'Slovenia' },
	{ value: 'svalbard and jan mayen', label: 'Svalbard and Jan Mayen' },
	{ value: 'slovakia', label: 'Slovakia' },
	{ value: 'sierra leone', label: 'Sierra Leone' },
	{ value: 'san marino', label: 'San Marino' },
	{ value: 'senegal', label: 'Senegal' },
	{ value: 'somalia', label: 'Somalia' },
	{ value: 'suriname', label: 'Suriname' },
	{ value: 'south sudan', label: 'South Sudan' },
	{ value: 'são tomé and príncipe', label: 'São Tomé and Príncipe' },
	{ value: 'el salvador', label: 'El Salvador' },
	{ value: 'sint maarten', label: 'Sint Maarten' },
	{ value: 'syria', label: 'Syria' },
	{ value: 'eswatini', label: 'Eswatini' },
	{ value: 'turks and caicos islands', label: 'Turks and Caicos Islands' },
	{ value: 'chad', label: 'Chad' },
	{ value: 'french southern territories', label: 'French Southern Territories' },
	{ value: 'togo', label: 'Togo' },
	{ value: 'thailand', label: 'Thailand' },
	{ value: 'tajikistan', label: 'Tajikistan' },
	{ value: 'tokelau', label: 'Tokelau' },
	{ value: 'timor-leste', label: 'Timor-Leste' },
	{ value: 'turkmenistan', label: 'Turkmenistan' },
	{ value: 'tunisia', label: 'Tunisia' },
	{ value: 'tonga', label: 'Tonga' },
	{ value: 'turkey', label: 'Turkey' },
	{ value: 'trinidad and tobago', label: 'Trinidad and Tobago' },
	{ value: 'tuvalu', label: 'Tuvalu' },
	{ value: 'taiwan', label: 'Taiwan' },
	{ value: 'tanzania', label: 'Tanzania' },
	{ value: 'ukraine', label: 'Ukraine' },
	{ value: 'uganda', label: 'Uganda' },
	{ value: 'united states minor outlying islands', label: 'United States Minor Outlying Islands' },
	{ value: 'united states', label: 'United States' },
	{ value: 'uruguay', label: 'Uruguay' },
	{ value: 'uzbekistan', label: 'Uzbekistan' },
	{ value: 'vatican city', label: 'Vatican City' },
	{ value: 'saint vincent and the grenadines', label: 'Saint Vincent and the Grenadines' },
	{ value: 'venezuela', label: 'Venezuela' },
	{ value: 'british virgin islands', label: 'British Virgin Islands' },
	{ value: 'u.s. virgin islands', label: 'U.S. Virgin Islands' },
	{ value: 'vietnam', label: 'Vietnam' },
	{ value: 'vanuatu', label: 'Vanuatu' },
	{ value: 'wallis and futuna', label: 'Wallis and Futuna' },
	{ value: 'samoa', label: 'Samoa' },
	{ value: 'yemen', label: 'Yemen' },
	{ value: 'mayotte', label: 'Mayotte' },
	{ value: 'south africa', label: 'South Africa' },
	{ value: 'zambia', label: 'Zambia' },
	{ value: 'zimbabwe', label: 'Zimbabwe' }
];
